model:
    arch: CAN
data:
    dataset: my
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 512
    path: your/path/to/ISPRS/Potsdam/dataset/
training:
    train_iters: 300000
    batch_size: 6
    val_interval: 1000
    n_workers: 16
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-3
        weight_decay: 0.0005
        momentum: 0.99

    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume: CAN_my_best_model.pkl
